[이현주] 마켓컬리 회원가입 엔드포인트 구현 완료
wecode-bootcamp-korea/15-1st-MarketBully-backend pull request #2
Opened 2020-12-18 08:45 UTC by hjulee12

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 엔드포인트 구현
  - 아이디(account)/비밀번호/이메일/휴대폰 정규식 이용하여 validation
  - 기존에 회원가입을 한 경우 오류메시지 전달(USER_EXISTS) 
  - 필수 입력사항 구현 및 선택 입력사항 default 값 지정
  		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- validation 조건
 - account: 6자 이상의 영문 또는 영문과 숫자 조합 
 - password: 10자 이상 입력, 영문/숫자/특수문자만 허용
 - 이메일: @, . 포함
 - 휴대폰번호: 11자리 입력
 - validation 조건에 맞지 않는 경우 invalid 에러 리턴

- 필수입력사항 누락 시 keyerror 리턴

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-18 08:56 UTC, lordmyshepherd requested changes

2020-12-18 08:56 UTC, lordmyshepherd commented on user/views.py
> +                    )
여주님! 회원가입할 때, gender, grade 데이터도 정규화해서 table을 만들어서 사용하신 것 너무 잘하셨습니다.
다만 전체 flow를 설명을 드리면, 
사용자가 처음에 회원가입 페이지에 들어오면, 프론트엔드에서 server에서 gender list와 grade list를 요청해서 받아가서 
drop down 버튼을 만들어줍니다.

그리고 회원가입을 진행하고 gender와 grade를 선택하고 회원가입 버튼을 누르면, 선택한 gender_id와 grade_id를 함께 서버에 보내줘야합니다. 
```suggestion
                User.objects.create(
                    account             = data['account'],
                    password            = hashed_pw,
                    name                = data['name'],
                    email               = data['email'],
                    phone_number        = data['phone_number'],
                    gender_id              = data['gender_id'],
                    birth_date          = birth_date,
                    recommender         = recommender,
                    event_name          = event_name,
                    grade_id               = data['grade_id']),
                    terms_and_condition = TermsAndCondition(id=1),
                    mileage             = 0
                    )
```

2020-12-19 06:12 UTC, hjulee12 commented on user/views.py
> +                    )
병민님, 말씀하신 부분 숙지 후 수정 완료 했습니다. 

또한 아이디(account), 비밀번호 정규표현식 등에 잘못된 부분이 있어 추가로 수정했고,
회원가입 시에 주소지를 입력하는 부분이 있었는데 주소 테이블이 따로 빠져있어 누락이 되어 있었습니다.

주소 테이블이 유저 테이블을 참조하고 있는 관계이며, 데이터 입력 시 주소테이블로 데이터 연동될 수 있게끔 구현완료 했습니다.

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +from my_settings import SECRET_KEY
순서대로 import 하는 객체들을 정렬 good! 파이썬과 장고, 장고와 내가 만든 클래스들 사이에 한 줄씩 띄워주세요

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +        return True
```suggestion
        return re.match(REGEX_ACCOUNT_1, account) and not re.match(REGEX_ACCOUNT_2, account):
```

파이썬에서는 반환 되는 값 자체가 boolean 일 경우나, Truthy, Falsy 한 값일 경우,  == False == None == 0등으로 평가하지 않고, 그 값을 그대로 사용합니다. 그 자체로도 True or False를 판단할 수 있기 때문입니다. False한 지 평가하실 때는 not 을 활용해보세요 :)

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +        return True
아래 다른 코드들도 마찬가지입니다.

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +
불필요한 간격은 약간의 가독성을 해칠 수 있습니다 :) 제거해주세요

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +                return JsonResponse({"message":"INVALID_PHONE_NUMBER"}, status=400)
꼼꼼하게 잘 돼네요! good!

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +                is_active=False
코드 간격 정렬해주세요

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +
깔끔한 코드를 위해 불필요한 공백은 제거해주세요

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +            return JsonResponse({"message":"SUCCESS"}, status=200)
데이터가 잘 생성되었음을 나타내는 status code 201 을 추천드립니다 :)

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +                user=User.objects.get(id=user_model.id),
FK는 `user_id`라는 컬럼으로도 지정할 수 있답니다 :)
그렇게 되면 User 클래스를 굳이 get 해오지도 않아도 id를 지정할 수 있습니다.

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +                )
User 객체 생성과 동시에 user_model이라는 변수에 담는 것 너무 좋네요!

2020-12-21 02:14 UTC, soheon-lee commented on user/views.py
> +                user=User.objects.get(id=user_model.id),
현주님 회원가입 하실 때 User와 Address를 동시에 생성하셔야 하는군요 :) 어려운 로직일 수 있는데 잘 하고 있으십니다.
현재 User와 Address를 생성함에 있어서 생길 수 있는 문제점이 하나 있습니다.
만약 90번째 줄에서 Address를 생성하다가 중간에 오류가 나거나, 컴퓨터 서버가 갑자기 꺼지는 돌발 상황이 생긴다면 어떻게 될까요?

User객체만 생기고, Address객체는 생성되지 않는 문제가 생길 수 있습니다. 혹시 이해되시나요?
그러나 우리는 이 회원가입 과정 중에 한 번이라도 오류가 나면 User도 생기지 않고 Address도 생기지 않아야 합니다.

두 테이블 연속해서 어떤 수정 사항이 생긴다면, 하나가 실패할 때는 다른 하나도 성공해서는 안됩니다.
이런 과정을 보장해주기 위해서 database에는 transaction이라는 기능이 있습니다 :) 한 번 공부해보시고, 도입해보시면 보다 완성도 있는 로직이 됩니다 👍

2020-12-22 05:33 UTC, soheon-lee commented on market_bully/urls.py
> +I   ]
오잉 이 `I`는 뭘까요..?

2020-12-22 05:33 UTC, soheon-lee commented on user/utils.py
> +            return func(self, request, *args, **kwargs)
`aceess_token`이 없으면 어떤 에러가 발생하는지 혹시 테스트 해보셨나요?

2020-12-22 05:33 UTC, soheon-lee commented on user/views.py
> +
goood!

2020-12-22 05:33 UTC, soheon-lee commented on user/views.py
> +            with transaction.atomic():  # user_model.save(), address.save() 중 하나만 실패해도 모든 commit rollback
메모용 혹은 공부용 주석은 제거해주시는 것이 좋습니다.
주석이 사용되는 때는, 코드만 보고서는 이해가 잘 안될 때 이해를 돕기 위해 작성하는데,
`transaction.atomic()`은 구문만 보고도 transaction을 시작한다는 것을 어렵지 않게 이해할 수 있기 때문에 주석이 꼭 필요할 것 같지 않네요 :)

2020-12-22 05:33 UTC, soheon-lee commented on user/views.py
> +
빈 공백이 필요한 위치가 아니라고 판단됩니다 :)

2020-12-22 05:33 UTC, soheon-lee commented on user/views.py
> +
사용자가 존재하지 않을 때 (이메일을 잘못 입력했을 때), 혹은 비밀번호가 틀렸을 때 서로 다른 에러 메세지와 에러 코드를 준다면, 보안상의 이슈가 생길 수 있습니다. 요즘 서비스를 생각해보시면, 비밀번호를 틀렸는지 이메일을 잘못 적었는지 명확히 구분해주지 않죠? 따라서 우리도 같은 방법으로 이메일이 틀렸을 떄와 비밀번호가 틀렸을 때 같은 메세지와 같은 에러 코드를 전달해주시는 것이 좋습니다 :)

2020-12-22 05:33 UTC, soheon-lee commented on user/views.py
> +#                account = User.objects.get(account=data["account"])
사용하지 않는 코드는 제거해주세요 :-) 이대로 merge 되면 다른 팀원의 컴퓨터에도 이 코드가 입력됩니다

2020-12-22 11:46 UTC, hjulee12 commented on user/views.py
> +#                account = User.objects.get(account=data["account"])
회원가입과 로그인 branch를 따로 나눠서 올리려고 signinview를 다 지웠는데 지워지지 않고 다 같이 push가 된 것 같아요 ㅠㅠ
꼼꼼히 보고 push하겠습니다아

2020-12-22 15:04 UTC, lordmyshepherd approved these changes

2020-12-22 15:04 UTC, lordmyshepherd commented
LGTM 👍 
고생 정말 많이 하셨습니다!
정규식을 마스터 하신 것 같습니다.

2020-12-22 15:05 UTC, merged