Add: 상품 리스트, MD 추천 상품, 카테고리 엔드포인트 구현 완료
wecode-bootcamp-korea/15-1st-MarketBully-backend pull request #9
Opened 2020-12-22 04:39 UTC by jacobjuhyunglee

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 상품 리스트, MD 추천, 카테고리 엔드포인트 구현 완료하였습니다.
- 		 
## 수정 사항들 자세한 내용
- 상품 리스트에서쿼리 스트링 파라미터 사용해 필터링 구현하였습니다.
- 프론트에서 카테고리와 MD추천 데이터를 원해 view 작성해주었습니다.

## 기타 질문 및 특이 사항
- 상품 디테일 머지 후 상품에 관련된 다른 뷰들을 작성해보았는데 잘 작성된 것인지 궁금합니다!
- FilterView로 `product=1`와 같이 url parameter 구현하려고 했었는데 잘 안되다가 쿼리스트링 파라미터를 알게되어 삼향연산자를 사용해 구현하였습니다. 이 부분이 맞게 사용된건지 알고 싶습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2020-12-22 06:07 UTC, soheon-lee commented on product/urls.py
> +                            )
```suggestion
from product.views  import (
    ProductDetailView,
    ProductListView,
    MdChoiceView,
    CategoryView,
)
```
한 탭 정도 띄우시면 가장 적절할 것 같습니다

2020-12-22 06:07 UTC, soheon-lee commented on product/views.py
> +            limit               = int(request.GET.get('limit', 4))
goood!

2020-12-22 06:07 UTC, soheon-lee commented on product/views.py
> +            subcategory_num     = request.GET.get('subcategory', None)
```suggestion
            subcategory_number     = request.GET.get('subcategory', None)
```
num을 보면 누구나 number임을 유추할 수 있지만, 그래도 최대한 축약어를 줄이시는 것이 좋습니다 :) 혹시 오해할 수 있기 때문입니다.
혹은 `subcategory_id`는 어떠신가요?

2020-12-22 06:07 UTC, soheon-lee commented on product/views.py
> +
이 부분은 아래 CategoryView가 하는 역할인 것 같은데 ProductListView에도 같이 포함되어 있는 이유가 있나요?
혹시 프로덕트 리스트 뷰에서 카테고리가 같이 나와야하기 때문이라면, 여전히 프로덕트 리스트 뷰에서는 카테고리 표출 기능을 빼신 후,

프론트분들에게 같은 페이지에서 카테고리를 호출하는 view와 프로덕트를 호출하는 view를 거의 동시에 연달아 호출하실 수 있는지 한 번 논의해보시길 바랍니다 :) 그 방향이 RESTful API에 조금 더 적합합니다. 한 번 토론 해보시길 추천드립니다

2020-12-22 06:07 UTC, soheon-lee commented on product/views.py
> +
이 VALUE_ERROR는 어떤 경우에 발생하는 에러였나요?

2020-12-22 06:07 UTC, soheon-lee commented on product/views.py
> +            products            = Product.objects.select_related('discount', 'subcategory').filter(subcategory=subcategory_num)if subcategory_num else Product.objects.all()
```suggestion
            products            = Product.objects.select_related('discount', 'subcategory').filter(subcategory=subcategory_num) if subcategory_num else Product.objects.all()
```

2020-12-22 07:14 UTC, jacobjuhyunglee commented on product/urls.py
> +                            )
align에 너무 목숨걸었네요... 수정했습니다! 👍

2020-12-22 07:17 UTC, jacobjuhyunglee commented on product/views.py
> +            limit               = int(request.GET.get('limit', 4))
🙈

2020-12-22 07:18 UTC, jacobjuhyunglee commented on product/views.py
> +            subcategory_num     = request.GET.get('subcategory', None)
축약어를 지양하는 위코드 컨벤션을 까먹었었군요😱
`subcategory_id`로 수정하였습니다!

2020-12-22 07:50 UTC, jacobjuhyunglee commented on product/views.py
> +            products            = Product.objects.select_related('discount', 'subcategory').filter(subcategory=subcategory_num)if subcategory_num else Product.objects.all()
수정하였습니다 👍

2020-12-22 08:15 UTC, jacobjuhyunglee commented on product/views.py
> +
ProductListView에서 카테고리 제거하였습니다! 👍 
사실 이전까지는 페이지의 url당 한 view만 사용가능한지 알아서 각 각 두 프론트엔드에게 넘겨주려 이렇게 만들었었는데 병민님께 물어보니 아니라고 하시더라구요!ㅎㅎ
API가 URL을 정의하지 않는다는 것을 이번에 꺠달았습니다!

2020-12-22 08:35 UTC, jacobjuhyunglee commented on product/views.py
> +
PR전 프론트엔드 요청으로 급하게 넣다보니 신중하게 사용하지 않았던 것 같습니다! 
뺴도록 하겠습니다!

2020-12-22 15:59 UTC, jamessoun93 requested changes
주형님 `.DS_Store` 발견했네요! 🚨

2020-12-22 15:59 UTC, jamessoun93 commented on product/views.py
> +            categories     = Category.objects.prefetch_related('subcategory_set')
이 부분은 쓰이는 곳이 없는 것 같네요 주형님!

2020-12-22 15:59 UTC, jamessoun93 commented on product/views.py
> +            'subcategory' : [{
```suggestion
            'subcategories' : [{
```

2020-12-23 01:55 UTC, soheon-lee commented
LGTM

2020-12-23 01:55 UTC, merged